@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class NOTIFICACAO {
   n_processo: varchar(20)
   statuss: varchar(50)
   motivo_de_notificacao: varchar(100)
   id_notificacao: int
}
class PARTE {
   n_processo: varchar(20)
   cpf: varchar(50)
   cnpj: varchar(50)
   parte: varchar(5)
   nome: varchar(50)
   e_mail: varchar(50)
   cep: varchar(50)
   numero: varchar(50)
   id_parte: int
}
class PROCESSO {
   orgao_julgado: varchar(20)
   valor_causa: varchar(50)
   nivel_sigilo: varchar(50)
   prioridade: varchar(50)
   n_processo: varchar(20)
}

NOTIFICACAO  -[#595959,plain]-^  PROCESSO    : "n_processo"
PARTE        -[#595959,plain]-^  PROCESSO    : "n_processo"
@enduml
